# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: "3.4"

services:
    backend:
        build:
            context: ./Backend
            target: production
        ports:
            - 8080:8080
        environment:
            - ASPNETCORE_URLS=http://+:80

    frontend:
        image: ${COMPOSE_PROJECT_NAME}-frontend:prod
        build:
            context: ./Frontend
            target: production
        ports:
            - 4000:4000
