version: "3.4"

services:
    backend:
        image: ${COMPOSE_PROJECT_NAME}-backend:dev
        build:
            context: .
            dockerfile: Backend/Dockerfile
            target: development
        ports:
            - 5000:8080
        depends_on:
            - db
        networks:
            - dev-network
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - DOTNET_USE_POLLING_FILE_WATCHER=1
        working_dir: /app
        volumes:
            - ./Backend:/app
            - /app/Backend/obj/
            - /app/Backend.Test/obj/
            - ~/.vsdbg:/remote_debugger:rw
        command: dotnet watch run --project Backend/Backend.csproj --no-launch-profile --no-restore

    frontend:
        image: ${COMPOSE_PROJECT_NAME}-frontend:dev
        build:
            context: .
            dockerfile: Frontend/Dockerfile
            target: development
        ports:
            - 4200:4200
        working_dir: /app
        volumes:
            - ./Frontend:/app
        command: npm run start

    db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=N0tStr0ng$ecreT
        ports:
            - "1433:1433"
        volumes:
            - mssql-volume:/var/opt/mssql/data
        restart: always
        networks:
            - dev-network
        user: root

networks:
    dev-network:
        driver: bridge

volumes:
    mssql-volume:
